### ISSUE TITLE
How do I change the background of GDM?

### ISSUE THREAD

**Issue by cafetestrest** [jtojnar/nixfiles#10]
Hi @jtojnar ,
Wanted to reach out to you to help me out in finding a way to setup background image for GDM using nixos configuration files, how can I accomplish so?

I was able to find this thread but unsure how to achive it: https://discourse.nixos.org/t/how-to-set-gnome-a-k-a-gdm-greeter-a-k-a-lockscreen-login-background-a-k-a-wallpaper/14289

Thank you.

**Comment by jtojnar** [comment]
Hi, did you try https://discourse.nixos.org/t/gdm-background-image-and-theme/12632/4?u=jtojnar? If you are still unable to make it work, please open a new thread on Discourse describing what you have tried and where you got stuck.
